# Generated by Django 4.2.23 on 2025-07-11 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('village_profile', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='tblroles',
            old_name='txtRole',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='tbluser',
            name='departmentId',
        ),
        migrations.RemoveField(
            model_name='tbluser',
            name='districtId',
        ),
        migrations.AddField(
            model_name='tbluser',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='village_profile.tbldistrict'),
        ),
        migrations.AddField(
            model_name='tbluser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.tblroles'),
        ),
        migrations.DeleteModel(
            name='tblUser_Roles',
        ),
        migrations.AddField(
            model_name='tbluser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.tbldepartment'),
        ),
    ]
