# Generated by Django 4.2.23 on 2025-07-11 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('village_profile', '0001_initial'),
        ('accounts', '0002_tbldepartment_rename_txtrole_tblroles_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluser',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='village_profile.tblvillage'),
        ),
    ]
