# Generated by Django 4.2.23 on 2025-07-14 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('village_profile', '0002_tblcircle_name_as_tblcircle_name_bn_and_more'),
        ('accounts', '0003_tbluser_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluser',
            name='circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='village_profile.tblcircle'),
        ),
        migrations.AddField(
            model_name='tbluser',
            name='gram_panchayat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='village_profile.tblgrampanchayat'),
        ),
    ]
