# Generated by Django 4.2.23 on 2025-07-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tbluser_circle_tbluser_gram_panchayat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbluser',
            name='department',
        ),
        migrations.AddField(
            model_name='tblroles',
            name='name_as',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tblroles',
            name='name_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='tblDepartment',
        ),
    ]
