# Generated by Django 4.2.23 on 2025-07-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_tbldepartment_tbluser_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_bn', models.CharField(blank=True, max_length=255, null=True)),
                ('name_as', models.CharField(blank=True, max_length=255, null=True)),
                ('div_id', models.CharField(blank=True, max_length=255, null=True)),
                ('class_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
