# Generated by Django 4.2.23 on 2025-07-15 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_tblmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tbldepartment')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tblmodule')),
            ],
        ),
    ]
