# Generated by Django 5.2.9 on 2026-01-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pra_main',
            name='village_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
