# Generated by Django 5.2.9 on 2026-01-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_pra_main_village_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='fgd_livelihood_summary',
            name='village_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fgd_wash_summary',
            name='village_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='line_department',
            name='village_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pra_assets',
            name='village_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pra_shelter',
            name='village_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
