# Generated by Django 5.2.9 on 2026-01-25 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_fgd_livelihood_summary_village_code_and_more'),
        ('village_profile', '0009_merge_20260109_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineDepartmentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='pra_shelter',
            old_name='contact_person',
            new_name='equipment',
        ),
        migrations.RemoveField(
            model_name='pra_assets',
            name='village_code',
        ),
        migrations.RemoveField(
            model_name='pra_shelter',
            name='alternate_power_supply_available',
        ),
        migrations.RemoveField(
            model_name='pra_shelter',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='pra_shelter',
            name='drinking_water_available',
        ),
        migrations.RemoveField(
            model_name='pra_shelter',
            name='name_of_shelter',
        ),
        migrations.RemoveField(
            model_name='pra_shelter',
            name='number_of_rooms',
        ),
        migrations.RemoveField(
            model_name='pra_shelter',
            name='toilet_facilities_available',
        ),
        migrations.RemoveField(
            model_name='pra_shelter',
            name='village_code',
        ),
        migrations.AddField(
            model_name='pra_assets',
            name='dist_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pra_assets',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pra_assets',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pra_assets',
            name='vill_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pra_assets',
            name='village_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pra_shelter',
            name='dist_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pra_shelter',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pra_shelter',
            name='name_of_the_owner',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pra_shelter',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pra_shelter',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pra_shelter',
            name='vill_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pra_shelter',
            name='village_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pra_assets',
            name='equipment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='LineDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vill_id', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village_profile.tblvillage')),
                ('section_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.linedepartmentmaster')),
            ],
        ),
        migrations.DeleteModel(
            name='Line_department',
        ),
    ]
