# Generated by Django 5.2.9 on 2026-01-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_linedepartmentmaster_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fgd_livelihood_summary',
            name='village_code',
        ),
        migrations.RemoveField(
            model_name='fgd_wash_summary',
            name='village_code',
        ),
        migrations.AddField(
            model_name='fgd_livelihood_summary',
            name='dist_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fgd_livelihood_summary',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fgd_livelihood_summary',
            name='vill_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fgd_livelihood_summary',
            name='village_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fgd_wash_summary',
            name='dist_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fgd_wash_summary',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fgd_wash_summary',
            name='vill_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fgd_wash_summary',
            name='village_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
