# Generated by Django 5.2.9 on 2026-01-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_remove_fgd_livelihood_summary_village_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pra_shelter',
            old_name='equipment',
            new_name='contact_person',
        ),
        migrations.RenameField(
            model_name='pra_shelter',
            old_name='name_of_the_owner',
            new_name='name_of_shelter',
        ),
        migrations.RemoveField(
            model_name='pra_assets',
            name='dist_id',
        ),
        migrations.RemoveField(
            model_name='pra_assets',
            name='district',
        ),
        migrations.RemoveField(
            model_name='pra_assets',
            name='state',
        ),
        migrations.RemoveField(
            model_name='pra_shelter',
            name='dist_id',
        ),
        migrations.RemoveField(
            model_name='pra_shelter',
            name='remark',
        ),
        migrations.AddField(
            model_name='pra_shelter',
            name='alternate_power_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pra_shelter',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pra_shelter',
            name='drinking_water_facility_available',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pra_shelter',
            name='number_of_rooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pra_shelter',
            name='toilet_facility_available',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
