# Generated by Django 5.2.9 on 2026-01-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_rename_equipment_pra_shelter_contact_person_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pra_shelter',
            old_name='contact_person',
            new_name='equipment',
        ),
        migrations.RenameField(
            model_name='pra_shelter',
            old_name='name_of_shelter',
            new_name='name_of_the_owner',
        ),
        migrations.RemoveField(
            model_name='pra_shelter',
            name='alternate_power_source',
        ),
        migrations.RemoveField(
            model_name='pra_shelter',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='pra_shelter',
            name='drinking_water_facility_available',
        ),
        migrations.RemoveField(
            model_name='pra_shelter',
            name='number_of_rooms',
        ),
        migrations.RemoveField(
            model_name='pra_shelter',
            name='toilet_facility_available',
        ),
        migrations.AddField(
            model_name='pra_assets',
            name='dist_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pra_assets',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pra_assets',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pra_shelter',
            name='dist_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pra_shelter',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
