# Generated by Django 5.2.9 on 2026-01-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_rename_equipment_pra_shelter_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pra_assets',
            name='asset_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
