# Generated by Django 5.2.9 on 2026-01-30 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_pra_assets_asset_count'),
        ('administrator', '0007_rename_contact_person_pra_shelter_equipment_and_more'),
    ]

    operations = [
    ]
