# Generated by Django 5.2.9 on 2026-02-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_rename_equipment_pra_shelter_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linedepartment',
            name='official_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
