# Generated by Django 5.2.9 on 2026-02-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_linedepartment_official_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linedepartment',
            name='official_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
