# Generated by Django 5.2.9 on 2026-02-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_alter_linedepartment_official_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pra_main',
            name='nearest_police_station_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
