# Generated by Django 5.2.9 on 2026-02-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_pra_main_nearest_police_station_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='pra_main',
            name='access_to_credit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pra_main',
            name='access_to_fair_price_input_supplies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pra_main',
            name='access_to_flood_resilient_seed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pra_main',
            name='access_to_health_service_including_vaccination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pra_main',
            name='access_to_high_quality_seeds',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pra_main',
            name='access_to_high_technology_farming_practices',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pra_main',
            name='access_to_knowledge_kvk_on_farming',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pra_main',
            name='access_to_market_input_produce',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pra_main',
            name='access_to_market_output_produce',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pra_main',
            name='access_to_scientific_methods_of_farming_practices',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pra_main',
            name='access_to_technology',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pra_main',
            name='agriculture_insurance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pra_main',
            name='diversity_of_crops',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pra_main',
            name='more_than_one_crop_a_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pra_main',
            name='sericulture_insurance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pra_main',
            name='weaving_equipment_insurance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
