# Generated by Django 5.2.9 on 2026-02-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_pra_main_access_to_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pra_main',
            name='agriculture_insurance',
        ),
        migrations.RemoveField(
            model_name='pra_main',
            name='diversity_of_crops',
        ),
        migrations.RemoveField(
            model_name='pra_main',
            name='more_than_one_crop_a_year',
        ),
    ]
