# Generated by Django 5.2.9 on 2026-02-12 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('village_profile', '0009_merge_20260109_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='MitigationInterventionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200)),
                ('subtheme', models.CharField(max_length=200)),
                ('vulnerable_asset', models.CharField(blank=True, max_length=200)),
                ('intervention_type', models.CharField(blank=True, max_length=200)),
                ('intervention_name', models.TextField()),
                ('display_note', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('default_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit_cost_rs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MitigationPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost_rs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_cost_rs', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('target_beneficiaries', models.IntegerField(blank=True, null=True)),
                ('priority_rank', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('location_text', models.CharField(blank=True, max_length=255)),
                ('timeline_start', models.DateField(blank=True, null=True)),
                ('timeline_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mitigation.mitigationinterventionmaster')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='village_profile.tblvillage')),
            ],
        ),
    ]
