# Generated by Django 4.2.23 on 2025-07-10 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblCircle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tblDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tblGramPanchayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village_profile.tblcircle')),
            ],
        ),
        migrations.CreateModel(
            name='tblVillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('gram_panchayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village_profile.tblgrampanchayat')),
            ],
        ),
        migrations.AddField(
            model_name='tblcircle',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village_profile.tbldistrict'),
        ),
    ]
