# Generated by Django 4.2.23 on 2025-07-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcircle',
            name='name_as',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tblcircle',
            name='name_bn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbldistrict',
            name='name_as',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbldistrict',
            name='name_bn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tblgrampanchayat',
            name='name_as',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tblgrampanchayat',
            name='name_bn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tblvillage',
            name='name_as',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tblvillage',
            name='name_bn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
