# Generated by Django 4.2.23 on 2025-07-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_profile', '0002_tblcircle_name_as_tblcircle_name_bn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldistrict',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbldistrict',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tblvillage',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tblvillage',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
