# Generated by Django 4.2.23 on 2025-08-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("village_profile", "0003_tbldistrict_latitude_tbldistrict_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tblvillage",
            name="code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
