# Generated by Django 6.0 on 2025-12-18 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_profile', '0005_tblvillage_created_at_tblvillage_layer_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblvillage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tblvillage',
            name='layer_name',
        ),
        migrations.RemoveField(
            model_name='tblvillage',
            name='mobileDBDistrictID',
        ),
        migrations.RemoveField(
            model_name='tblvillage',
            name='mobileDBVillageID',
        ),
        migrations.RemoveField(
            model_name='tblvillage',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tblvillage',
            name='userID',
        ),
        migrations.CreateModel(
            name='district_village_mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileDBVillageID', models.CharField(blank=True, max_length=100, null=True)),
                ('mobileDBDistrictID', models.CharField(blank=True, max_length=100, null=True)),
                ('layer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village_profile.tblcircle')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village_profile.tbldistrict')),
                ('gram_panchayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village_profile.tblgrampanchayat')),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village_profile.tblvillage')),
            ],
        ),
    ]
