# Generated by Django 6.0 on 2025-12-18 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_profile', '0006_remove_tblvillage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='district_village_mapping',
            name='district_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='district_village_mapping',
            name='village_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbldistrict',
            name='district_layer_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbldistrict',
            name='mobileDBDistrictID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='district_village_mapping',
            name='circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='village_profile.tblcircle'),
        ),
        migrations.AlterField(
            model_name='district_village_mapping',
            name='gram_panchayat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='village_profile.tblgrampanchayat'),
        ),
        migrations.AlterField(
            model_name='district_village_mapping',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='village_profile.tblvillage'),
        ),
    ]
