# Generated by Django 5.2.9 on 2026-01-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_profile', '0007_district_village_mapping_district_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblvillage',
            name='geojson_file',
            field=models.FileField(blank=True, null=True, upload_to='village_geojson/'),
        ),
    ]
