# Generated by Django 5.2.9 on 2026-01-09 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('village_profile', '0002_add_geojson_file'),
        ('village_profile', '0008_tblvillage_geojson_file'),
    ]

    operations = [
    ]
