# Generated by Django 4.2.23 on 2025-07-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_training_activities_status',
            name='implemented_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_training_activities_status',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_training_activities_status',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Scheduled', 'Scheduled')], default='Scheduled', max_length=55),
        ),
    ]
