# Generated by Django 4.2.23 on 2025-07-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_tbl_training_activities_status_implemented_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_training_activities',
            name='name_as',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='tbl_training_activities',
            name='name_bn',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
    ]
