# Generated by Django 4.2.23 on 2025-07-11 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('village_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Rescue_Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=555)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Rescue_Equipment_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Already Existing', 'Already Existing'), ('To be procured', 'To be procured'), ('Procured', 'Procured')], default='To be procured', max_length=55)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rescue_equipment.tbl_rescue_equipment')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village_profile.tblvillage')),
            ],
        ),
    ]
