# Generated by Django 4.2.23 on 2025-07-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue_equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_rescue_equipment_status',
            name='status',
        ),
        migrations.AddField(
            model_name='tbl_rescue_equipment',
            name='specification',
            field=models.CharField(max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='tbl_rescue_equipment',
            name='task_force',
            field=models.CharField(max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='tbl_rescue_equipment_status',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
