# Generated by Django 4.2.23 on 2025-07-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue_equipment', '0002_remove_tbl_rescue_equipment_status_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_rescue_equipment',
            name='name_as',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbl_rescue_equipment',
            name='name_bn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbl_rescue_equipment',
            name='specification_as',
            field=models.CharField(max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='tbl_rescue_equipment',
            name='specification_bn',
            field=models.CharField(max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='tbl_rescue_equipment',
            name='task_force_as',
            field=models.CharField(max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='tbl_rescue_equipment',
            name='task_force_bn',
            field=models.CharField(max_length=555, null=True),
        ),
    ]
