# Generated by Django 4.2.23 on 2025-07-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoserverLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('layer_name', models.CharField(max_length=255)),
                ('workspace', models.CharField(max_length=255)),
            ],
        ),
    ]
