# Generated by Django 4.2.23 on 2025-07-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoserverlayers',
            name='title_as',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='geoserverlayers',
            name='title_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
