# Generated by Django 5.2.9 on 2026-01-19 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0002_geoserverlayers_title_as_geoserverlayers_title_bn'),
        ('village_profile', '0009_merge_20260109_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='village_flood_raster_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raster_file', models.FileField(upload_to='pipeline_data/flood_raster/')),
                ('layer_name', models.CharField(max_length=255)),
                ('workspace', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village_profile.tblvillage')),
            ],
        ),
    ]
