# Generated by Django 5.2.9 on 2026-01-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0003_village_flood_raster_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village_flood_raster_files',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='village_flood_raster_files',
            name='layer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='village_flood_raster_files',
            name='workspace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
