# Generated by Django 5.2.9 on 2026-02-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0004_alter_village_flood_raster_files_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='village_flood_raster_files',
            name='flood_map_image',
            field=models.FileField(blank=True, null=True, upload_to='maps/'),
        ),
    ]
