# Generated by Django 5.2.9 on 2026-02-03 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0005_village_flood_raster_files_flood_map_image'),
        ('village_profile', '0007_district_village_mapping_district_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='district_wind_raster_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raster_file', models.FileField(upload_to='pipeline_data/wind_raster/')),
                ('wind_map_image', models.FileField(blank=True, null=True, upload_to='maps/')),
                ('layer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('workspace', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, blank=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village_profile.tbldistrict')),
            ],
        ),
        migrations.CreateModel(
            name='district_eq_raster_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raster_file', models.FileField(upload_to='pipeline_data/eq_raster/')),
                ('eq_map_image', models.FileField(blank=True, null=True, upload_to='maps/')),
                ('layer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('workspace', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, blank=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village_profile.tbldistrict')),
            ],
        ),
    ]
