# Generated by Django 5.2.9 on 2026-02-04 13:48

import layers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0006_district_wind_raster_file_and_eq_raster_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district_eq_raster_file',
            name='eq_map_image',
            field=models.FileField(blank=True, null=True, upload_to=layers.models.eq_map_upload_to),
        ),
        migrations.AlterField(
            model_name='district_wind_raster_file',
            name='wind_map_image',
            field=models.FileField(blank=True, null=True, upload_to=layers.models.wind_map_upload_to),
        ),
        migrations.AlterField(
            model_name='village_flood_raster_files',
            name='flood_map_image',
            field=models.FileField(blank=True, null=True, upload_to=layers.models.flood_map_upload_to),
        ),
    ]
