# Generated by Django 5.2.9 on 2026-02-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0007_alter_district_eq_raster_file_eq_map_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district_eq_raster_file',
            name='raster_file',
            field=models.FileField(upload_to='pipeline_data/eq_raster/eq.tif'),
        ),
    ]
