# Generated by Django 5.2.9 on 2026-02-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0008_alter_district_eq_raster_file_raster_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district_eq_raster_file',
            name='raster_file',
            field=models.FileField(blank=True, default='pipeline_data/eq_raster/eq.tif', null=True, upload_to='pipeline_data/eq_raster/'),
        ),
        migrations.AlterField(
            model_name='district_wind_raster_file',
            name='raster_file',
            field=models.FileField(blank=True, default='pipeline_data/wind_raster/Wing.tif', null=True, upload_to='pipeline_data/wind_raster/'),
        ),
    ]
