# Generated by Django 5.2.9 on 2026-02-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0009_alter_district_eq_raster_file_raster_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district_wind_raster_file',
            name='raster_file',
            field=models.FileField(blank=True, default='pipeline_data/wind_raster/Wind.tif', null=True, upload_to='pipeline_data/wind_raster/'),
        ),
    ]
