# Generated by Django 5.2.9 on 2026-02-06 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0010_alter_district_wind_raster_file_raster_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district_eq_raster_file',
            name='eq_map_image',
        ),
        migrations.RemoveField(
            model_name='district_wind_raster_file',
            name='wind_map_image',
        ),
        migrations.RemoveField(
            model_name='village_flood_raster_files',
            name='flood_map_image',
        ),
    ]
