# Generated by Django 5.2.9 on 2026-02-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0011_remove_layer_map_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village_flood_raster_files',
            name='raster_file',
            field=models.FileField(blank=True, null=True, upload_to='pipeline_data/flood_raster/'),
        ),
    ]
