# Generated by Django 5.2 on 2025-09-10 10:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShapefileElectricPole',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('material', models.CharField(blank=True, max_length=254, null=True)),
                ('remarks', models.CharField(blank=True, max_length=254, null=True)),
                ('photo_id', models.CharField(blank=True, max_length=254, null=True)),
                ('flood', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vill_name', models.CharField(blank=True, max_length=50, null=True)),
                ('vill_id', models.CharField(blank=True, max_length=20, null=True)),
                ('dist_name', models.CharField(blank=True, max_length=40, null=True)),
                ('dist_id', models.CharField(blank=True, max_length=20, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'electricpoles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShapefileTransformer',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('material', models.CharField(blank=True, max_length=254, null=True)),
                ('vill_name', models.CharField(blank=True, max_length=50, null=True)),
                ('vill_id', models.CharField(blank=True, max_length=20, null=True)),
                ('dist_name', models.CharField(blank=True, max_length=40, null=True)),
                ('dist_id', models.CharField(blank=True, max_length=20, null=True)),
                ('flood', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'transformer',
                'managed': False,
            },
        ),
    ]
