# Generated by Django 5.2 on 2025-09-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapefiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExposureRiver',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid_1', models.FloatField(blank=True, null=True)),
                ('class_name', models.CharField(blank=True, max_length=254, null=True)),
                ('village', models.CharField(blank=True, max_length=80, null=True)),
                ('district', models.CharField(blank=True, max_length=80, null=True)),
                ('vill_id', models.CharField(blank=True, max_length=15, null=True)),
                ('rev_circ', models.CharField(blank=True, max_length=50, null=True)),
                ('dist_id', models.CharField(blank=True, max_length=15, null=True)),
                ('rev_circid', models.CharField(blank=True, max_length=15, null=True)),
                ('shape_leng', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('shape_area', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('length_m', models.FloatField(blank=True, null=True)),
                ('erosion_m', models.FloatField(blank=True, null=True)),
                ('acretion_m', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exposure_river',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExposureRoadVillage',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('village_na', models.CharField(blank=True, max_length=50, null=True)),
                ('length_m', models.FloatField(blank=True, null=True)),
                ('affleng_m', models.FloatField(blank=True, null=True)),
                ('vill_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'exposure_road_village',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PraBoundary',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('village', models.CharField(blank=True, max_length=80, null=True)),
                ('district', models.CharField(blank=True, max_length=80, null=True)),
                ('area_sqkm', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('dist_id', models.FloatField(blank=True, null=True)),
                ('vill_id', models.CharField(blank=True, max_length=15, null=True)),
                ('rev_circ', models.CharField(blank=True, max_length=50, null=True)),
                ('rev_circid', models.CharField(blank=True, max_length=15, null=True)),
                ('area_ha', models.FloatField(blank=True, null=True)),
                ('affarea_ha', models.FloatField(blank=True, null=True)),
                ('shalt_adq', models.FloatField(blank=True, null=True)),
                ('elec_poles', models.IntegerField(blank=True, null=True)),
                ('aff_poles', models.IntegerField(blank=True, null=True)),
                ('transf', models.IntegerField(blank=True, null=True)),
                ('aff_transf', models.IntegerField(blank=True, null=True)),
                ('bridge', models.IntegerField(blank=True, null=True)),
                ('aff_bridge', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pra_boundary',
                'managed': False,
            },
        ),
    ]
