# Generated by Django 4.2.23 on 2025-08-19 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("village_profile", "0004_alter_tblvillage_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="field_images/%Y/%m/%d/", verbose_name="Image File"
                    ),
                ),
                (
                    "upload_datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Upload Date & Time"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Livelihood", "Livelihood"),
                            ("Educational facilities", "Educational facilities"),
                            (
                                "River bank protection/erosion",
                                "River bank protection/erosion",
                            ),
                            ("Infrastructure", "Infrastructure"),
                            ("housing", "housing"),
                            (
                                "PRA and field consultations",
                                "PRA and field consultations",
                            ),
                            ("PRA Map", "PRA Map"),
                        ],
                        max_length=50,
                        verbose_name="Image Category",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Image Name (Optional)",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded By",
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_images",
                        to="village_profile.tblvillage",
                        verbose_name="Associated Village",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Image",
                "verbose_name_plural": "Field Images",
                "ordering": ["-upload_datetime"],
            },
        ),
        migrations.AddConstraint(
            model_name="fieldimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("name__isnull", True)),
                fields=("village", "category"),
                name="unique_village_category",
            ),
        ),
        migrations.AddConstraint(
            model_name="fieldimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("name__isnull", False)),
                fields=("village", "category", "name"),
                name="unique_village_category_name",
            ),
        ),
    ]
