# Generated by Django 4.2.23 on 2025-08-19 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("field_images", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="fieldimage", name="unique_village_category",
        ),
        migrations.RemoveConstraint(
            model_name="fieldimage", name="unique_village_category_name",
        ),
    ]
