# Generated by Django 4.2.23 on 2025-08-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("field_images", "0002_remove_fieldimage_unique_village_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldimage",
            name="image",
            field=models.ImageField(
                upload_to="field_images/", verbose_name="Image File"
            ),
        ),
    ]
