# Generated by Django 5.2.9 on 2026-02-04 08:21

import field_images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_images', '0003_alter_fieldimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldimage',
            name='image',
            field=models.ImageField(upload_to=field_images.models.field_image_upload_to, verbose_name='Image File'),
        ),
    ]
