# Generated by Django 4.2.23 on 2025-08-11 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("village_profile", "0004_alter_tblvillage_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskForce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=150)),
                ("father_name", models.CharField(max_length=150)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "position_responsibility",
                    models.CharField(
                        choices=[
                            ("Team member", "Team member"),
                            ("Team leader", "Team leader"),
                        ],
                        max_length=50,
                    ),
                ),
                ("mobile_number", models.CharField(max_length=15)),
                (
                    "team_type",
                    models.CharField(
                        choices=[
                            ("VLCDMC", "VLCDMC"),
                            ("Search & rescue", "Search & rescue"),
                            ("Relief management team", "Relief management team"),
                            ("Shelter Management team", "Shelter Management team"),
                            ("First Aid team", "First Aid team"),
                            ("Water & Sanitation", "Water & Sanitation"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taskforces",
                        to="village_profile.tblvillage",
                    ),
                ),
            ],
        ),
    ]
