# Generated by Django 4.2.23 on 2025-08-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vdmp_progress", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tblvdmp_activity",
            name="order",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
