# Generated by Django 6.0 on 2025-12-18 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_progress', '0002_tblvdmp_activity_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblVDMP_Activity_Import_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows_imported', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('processing_time', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vdmp_progress.tblvdmp_activity')),
                ('activity_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vdmp_progress.tblvdmp_activity_status')),
            ],
        ),
    ]
