# Generated by Django 6.0 on 2025-12-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_progress', '0003_tblvdmp_activity_import_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblvdmp_activity_import_status',
            name='error_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
