# Generated by Django 6.0 on 2025-12-30 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_progress', '0004_tblvdmp_activity_import_status_error_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='house_type',
            fields=[
                ('house_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('house_type', models.CharField(max_length=100)),
                ('per_unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discription', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='house_type_combination_mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wall_type', models.CharField(max_length=100)),
                ('roof_type', models.CharField(max_length=100)),
                ('floor_type', models.CharField(max_length=100)),
                ('combo_key', models.CharField(max_length=300)),
                ('is_New', models.BooleanField(default=False)),
                ('house_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vdmp_progress.house_type')),
            ],
        ),
    ]
