# Generated by Django 6.0 on 2025-12-30 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_progress', '0005_house_type_house_type_combination_mapping'),
        ('village_profile', '0007_district_village_mapping_district_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EQ_MDR_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PGA_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('MDR_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('house_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vdmp_progress.house_type')),
            ],
        ),
        migrations.CreateModel(
            name='flood_MDR_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flood_depth_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('MDR_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('house_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vdmp_progress.house_type')),
            ],
        ),
        migrations.CreateModel(
            name='wind_MDR_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind_speed_kmph', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('MDR_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('house_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vdmp_progress.house_type')),
            ],
        ),
        migrations.CreateModel(
            name='Risk_Assessment_Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('village_name', models.CharField(blank=True, max_length=255, null=True)),
                ('village_code', models.CharField(blank=True, max_length=255, null=True)),
                ('point_id', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_type', models.CharField(choices=[('household', 'Household'), ('commercial', 'Commercial'), ('critical_facility', 'Critical Facility')], max_length=20)),
                ('wall_type', models.CharField(blank=True, max_length=255, null=True)),
                ('roof_type', models.CharField(blank=True, max_length=255, null=True)),
                ('floor_type', models.CharField(blank=True, max_length=255, null=True)),
                ('building_length_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('building_width_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('building_area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('house_type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('replacement_cost_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('eq_hazard', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('wind_hazard', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('flood_hazard', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('flood_hazard_mdr', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('eq_hazard_mdr', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('wind_hazard_mdr', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('flood_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('eq_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('wind_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('house_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vdmp_progress.house_type')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village_profile.tblvillage')),
            ],
            options={
                'indexes': [models.Index(fields=['village', 'asset_type'], name='vdmp_progre_village_d26481_idx'), models.Index(fields=['reference_id'], name='vdmp_progre_referen_3d8de3_idx')],
                'unique_together': {('reference_id', 'asset_type', 'village')},
            },
        ),
    ]
