# Generated by Django 5.2.9 on 2025-12-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_progress', '0006_eq_mdr_table_flood_mdr_table_wind_mdr_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eq_mdr_table',
            name='MDR_value',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='flood_mdr_table',
            name='MDR_value',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='risk_assessment_result',
            name='eq_hazard',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='risk_assessment_result',
            name='eq_hazard_mdr',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='risk_assessment_result',
            name='flood_hazard',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='risk_assessment_result',
            name='flood_hazard_mdr',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='risk_assessment_result',
            name='wind_hazard',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='risk_assessment_result',
            name='wind_hazard_mdr',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wind_mdr_table',
            name='MDR_value',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
    ]
