# Generated by Django 5.2.9 on 2026-02-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_progress', '0009_risk_assessment_result_erosion_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='house_type_combination_mapping',
            name='plplinth_or_stilt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
