# Generated by Django 5.2.9 on 2026-02-25 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_progress', '0010_house_type_combination_mapping_plplinth_or_stilt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house_type_combination_mapping',
            old_name='plplinth_or_stilt',
            new_name='plinth_or_stilt',
        ),
    ]
