# Generated by Django 6.0 on 2026-03-12 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_progress', '0011_rename_plplinth_or_stilt_house_type_combination_mapping_plinth_or_stilt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalFacilityUnitCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_cost_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('house_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vdmp_progress.house_type')),
            ],
        ),
    ]
