# Generated by Django 5.2.9 on 2026-03-17 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_progress', '0002_house_type_building_type'),
        ('vdmp_progress', '0012_critical_facility_unit_cost'),
    ]

    operations = [
    ]
