# Generated by Django 4.2.23 on 2025-08-14 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("village_profile", "0004_alter_tblvillage_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="VillageRoadInfoErosion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("district_name", models.CharField(max_length=100)),
                ("district_code", models.CharField(max_length=20)),
                ("village_name", models.CharField(max_length=100)),
                ("village_code", models.CharField(max_length=20)),
                ("road_surface_type", models.CharField(max_length=100)),
                ("road_constructed_by", models.CharField(max_length=100)),
                ("road_length_m", models.FloatField()),
                ("erosion_class", models.CharField(max_length=50)),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="village_profile.tblvillage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VillageRoadInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("district_name", models.CharField(max_length=100)),
                ("district_code", models.CharField(max_length=20)),
                ("village_name", models.CharField(max_length=100)),
                ("village_code", models.CharField(max_length=20)),
                ("road_surface_type", models.CharField(max_length=100)),
                ("road_constructed_by", models.CharField(max_length=100)),
                ("road_length_m", models.FloatField()),
                ("flood_depth_m", models.FloatField(blank=True, null=True)),
                ("flood_class", models.CharField(max_length=50)),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="village_profile.tblvillage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VillageListOfAllTheDistricts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "district_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "revenue_circle",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "village_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "district_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "village_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "circle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("block_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "distance_from_headquarter",
                    models.FloatField(
                        blank=True, help_text="Distance in kilometers", null=True
                    ),
                ),
                (
                    "total_area",
                    models.FloatField(
                        blank=True,
                        help_text="Total area in square kilometers",
                        null=True,
                    ),
                ),
                (
                    "average_elevation",
                    models.FloatField(
                        blank=True, help_text="Elevation in meters", null=True
                    ),
                ),
                ("topography", models.TextField(blank=True, null=True)),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="village_profile.tblvillage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transformer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "village_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "district_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "district_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "village_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "transformer_site_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("latitude", models.CharField(blank=True, max_length=255, null=True)),
                ("longitude", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "flood_depth_m",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "flood_class",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "erosion_class",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="village_profile.tblvillage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HouseholdSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dist_code", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "village_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("point_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "property_owner",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "name_of_person",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "name_of_hohh",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("photo", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "data_access",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("community", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "social_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "economic_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("wall_type", models.CharField(blank=True, max_length=255, null=True)),
                ("roof_type", models.CharField(blank=True, max_length=255, null=True)),
                ("floor_type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "plinth_or_stilt",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "plinth_or_stilt_height_ft",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "number_of_storeys",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "number_of_males_including_children",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "number_of_females_including_children",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "children_below_6_years",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "senior_citizens",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "pregnant_women",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "lactating_women",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "persons_with_disability_or_chronic_disease",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "drinking_water_source",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sanitation_facility",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "toilet_wall_material",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "toilet_roof_material",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "digital_media_owned",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "house_has_electric_connection",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "source_of_electricity",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "own_agriculture_land",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "area_of_agriculture_land_owned_bigha",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "land_area_annually_cultivated_bigha",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "crops_cultivated",
                    models.CharField(blank=True, max_length=1055, null=True),
                ),
                (
                    "specify_other",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "number_of_crops_normally_raised_every_year",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "livelihood_primary",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "livelihood_secondary",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "do_you_have_big_cattle_cattle_buffalo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "number_of_big_cattle_animals",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "do_you_have_small_cattle_goat_sheep_pig",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "number_of_small_cattle_animals",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "do_you_have_poultry_chicken_and_duck",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "number_of_poultry_animals",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "approximate_income_earned_every_year_inr",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "expense_on_education",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "expense_on_health",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "expense_on_food",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "expense_on_tobacco_liquor",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "expense_on_house_repair",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "expense_on_festival_marriage_and_other_social_occassions",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "amount_spent_for_agriculture_livestock",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "loss_due_to_flood",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "loan_availed",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "loan_amount",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "loan_purpose",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "house_affected_by_flood",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "economic_loss_to_your_house_due_to_flood",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "amount_towards_flood_recovery_expenditure",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "maximum_flood_height_in_house_ft",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "year_in_which_maximum_flood_experience_in_your_house",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "your_agriculture_affected_by_flood",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "maximum_flood_height_experience_in_your_agriculture_ft",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "year_in_which_max_flood_experience_in_your_agriculture_land",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "duration_of_flood_stay_in_your_agriculture_field",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "other_natural_hazards_directly_impacting_you_and_family",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "house_vulnerable_to_erosion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "your_agriculture_field_vulnerable_to_erosion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "building_quality",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "foundation_quality",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "number_of_small_buildings_of_the_household",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "occupa_ncy_type_of_small_building",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "presence_of_grain_bank",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "plinth_height_of_grain_bank_ft",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "wall_material_of_grain_bank",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "roof_material_of_grain_bank",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "flood_depth_m",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "flood_class",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "erosion_class",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("loan_class", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "agrculture_land_class",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "loan_class_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "fld_hh_class",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "repair_class",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "economic_loss_hh",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "loss_agricultire_livlihood",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("big_cattle", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "small_cattle",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("house_type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "income_class",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "crops_diversity",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "Sanitation_Type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="village_profile.tblvillage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ElectricPole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "village_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "district_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "district_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "village_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("uid", models.CharField(blank=True, max_length=255, null=True)),
                ("latitude", models.CharField(blank=True, max_length=255, null=True)),
                ("longitude", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "electric_pole_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "electric_pole_material",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "remarks_on_pole_condition",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("photo", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "flood_depth_m",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "flood_class",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "erosion_class",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="village_profile.tblvillage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Critical_Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "district_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "district_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "village_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "village_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("point_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "occupancy_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("photo", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "name_of_building",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "incharge_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("wall_type", models.CharField(blank=True, max_length=255, null=True)),
                ("floor_type", models.CharField(blank=True, max_length=255, null=True)),
                ("roof_type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "plinth_or_stilt",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "plinth_or_stilt_height_ft",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "drinking_water_source",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "house_has_electric_connection",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "source_of_electricity",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "number_of_rooms",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "average_room_length_ft",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "average_room_width_ft",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "kitchen_facility",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "toilet_facility",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "number_of_toilets",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "water_facility_in_toilet",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "electricity_facility_in_toilet",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "building_affected_by_normal_flood",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "used_as_a_flood_emergency_shelter",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "access_road_during_flood",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "building_quality",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "foundation_quality",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "flood_depth_m",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "flood_class",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "erosion_class",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="village_profile.tblvillage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Commercial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "district_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "village_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "district_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "village_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("point_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "type_of_occupancy",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "type_of_occupancy_others",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "property_owner",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "name_of_person",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("photo", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "name_of_the_building",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "name_of_the_in_charge",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "phone_number_of_the_in_charge",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("wall_type", models.CharField(blank=True, max_length=255, null=True)),
                ("floor_type", models.CharField(blank=True, max_length=255, null=True)),
                ("roof_type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "plinth_above_ground",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "plinth_above_ground_stilt_height_in_ft",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "building_affected_by_normal_flood",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "approximate_content_value_inr",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "approximate_value_business_per_year",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "average_room_width_ft",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "average_room_length_ft",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "building_quality",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "foundation_quality",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "access_road_during_flood",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "flood_depth_m",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "erosion_class",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="village_profile.tblvillage",
                    ),
                ),
            ],
        ),
    ]
