# Generated by Django 4.2.23 on 2025-08-27 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('village_profile', '0004_alter_tblvillage_code'),
        ('vdmp_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VDMP_Maps_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_of_building', models.FileField(blank=True, max_length=255, null=True, upload_to='maps/distribution_of_building/')),
                ('road_infrastructure', models.FileField(blank=True, max_length=255, null=True, upload_to='maps/road_infrastructure/')),
                ('landuse', models.FileField(blank=True, max_length=255, null=True, upload_to='maps/landuse/')),
                ('flood_erosion', models.FileField(blank=True, max_length=255, null=True, upload_to='maps/flood_erosion/')),
                ('wind_hazard', models.FileField(blank=True, max_length=255, null=True, upload_to='maps/wind_hazard/')),
                ('earthquake_hazard', models.FileField(blank=True, max_length=255, null=True, upload_to='maps/earthquake_hazard/')),
                ('village', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='village_profile.tblvillage')),
            ],
        ),
    ]
