# Generated by Django 4.2.23 on 2025-08-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0002_vdmp_maps_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdmp_maps_data',
            name='electrical_infrastructure',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='maps/electrical_infrastructure/'),
        ),
        migrations.AddField(
            model_name='vdmp_maps_data',
            name='essential_facilities',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='maps/essential_facilities/'),
        ),
    ]
