# Generated by Django 5.2 on 2025-09-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0003_vdmp_maps_data_electrical_infrastructure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('spatial_id', models.CharField(blank=True, max_length=255, null=True)),
                ('spatial_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('polygon_id', models.CharField(blank=True, max_length=255, null=True)),
                ('village_id', models.CharField(blank=True, max_length=255, null=True)),
                ('village_name', models.CharField(blank=True, max_length=255, null=True)),
                ('district_name', models.CharField(blank=True, max_length=255, null=True)),
                ('survey_id', models.CharField(blank=True, max_length=255, null=True)),
                ('geometry', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('under_id', models.CharField(blank=True, max_length=255, null=True)),
                ('unique_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('form_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tab_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tab_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bridge_surface_type', models.CharField(blank=True, max_length=255, null=True)),
                ('length_meters', models.CharField(blank=True, max_length=255, null=True)),
                ('width_meters', models.CharField(blank=True, max_length=255, null=True)),
                ('photographs', models.CharField(blank=True, max_length=255, null=True)),
                ('bridge_pillar_material', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_pillars', models.CharField(blank=True, max_length=255, null=True)),
                ('deck_material', models.CharField(blank=True, max_length=255, null=True)),
                ('condition_of_deck', models.CharField(blank=True, max_length=255, null=True)),
                ('general_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('status_access_part', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
