# Generated by Django 5.2 on 2025-09-10 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0004_bridgesurvey'),
        ('village_profile', '0004_alter_tblvillage_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bridgesurvey',
            old_name='village_id',
            new_name='village_code',
        ),
        migrations.AddField(
            model_name='bridgesurvey',
            name='village',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='village_profile.tblvillage'),
            preserve_default=False,
        ),
    ]
