# Generated by Django 5.2 on 2025-09-12 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0005_rename_village_id_bridgesurvey_village_code_and_more'),
        ('village_profile', '0004_alter_tblvillage_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk_Assesment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.CharField(blank=True, max_length=255, null=True)),
                ('village_code', models.CharField(blank=True, max_length=100, null=True)),
                ('hazard', models.CharField(blank=True, max_length=100, null=True)),
                ('exposure_type', models.CharField(blank=True, max_length=100, null=True)),
                ('total_exposure_value_inr_crore', models.CharField(blank=True, max_length=100, null=True)),
                ('loss_inr_crore', models.CharField(blank=True, max_length=100, null=True)),
                ('loss_percent_wrt_exposure_value', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village_profile.tblvillage')),
            ],
        ),
    ]
