# Generated by Django 6.0 on 2025-12-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0006_risk_assesment'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdsurvey',
            name='form_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='householdsurvey',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
