# Generated by Django 6.0 on 2025-12-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0007_householdsurvey_form_id_householdsurvey_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_db_attribute_id', models.IntegerField()),
                ('attribute_text', models.CharField(blank=True, max_length=500, null=True)),
                ('alias_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(choices=[('HouseholdSurvey', 'Household Survey'), ('Commercial', 'Commercial'), ('Transformer', 'Transformer'), ('Critical_Facility', 'Critical_Facility'), ('ElectricPole', 'ElectricPole'), ('VillageListOfAllTheDistricts', 'VillageListOfAllTheDistricts'), ('VillageRoadInfo', 'VillageRoadInfo'), ('BridgeSurvey', '')], max_length=50)),
                ('is_calculated', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('mobile_db_attribute_id', 'model_name')},
            },
        ),
    ]
