# Generated by Django 6.0 on 2025-12-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0008_attributemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributemapping',
            name='tab_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attributemapping',
            name='tab_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
