# Generated by Django 6.0 on 2025-12-23 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0009_attributemapping_tab_id_attributemapping_tab_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attributemapping',
            unique_together={('mobile_db_attribute_id',)},
        ),
    ]
