# Generated by Django 6.0 on 2025-12-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0010_alter_attributemapping_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attributemapping',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attributemapping',
            name='mobile_db_attribute_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
