# Generated by Django 6.0 on 2025-12-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0012_commercial_form_id_commercial_unique_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridgesurvey',
            name='district_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bridgesurvey',
            name='point_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
