# Generated by Django 6.0 on 2025-12-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0014_bridgesurvey_latitude_bridgesurvey_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributemapping',
            name='model_name',
            field=models.CharField(choices=[('HouseholdSurvey', 'Household Survey'), ('Commercial', 'Commercial'), ('Transformer', 'Transformer'), ('Critical_Facility', 'Critical_Facility'), ('ElectricPole', 'ElectricPole'), ('VillageListOfAllTheDistricts', 'VillageListOfAllTheDistricts'), ('VillageRoadInfo', 'VillageRoadInfo'), ('BridgeSurvey', ''), ('others', 'others')], max_length=50),
        ),
    ]
