# Generated by Django 6.0 on 2025-12-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0015_alter_attributemapping_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdsurvey',
            name='build_area_meter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='householdsurvey',
            name='building_length_meter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='householdsurvey',
            name='building_width_meter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
