# Generated by Django 6.0 on 2025-12-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0016_householdsurvey_build_area_meter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdsurvey',
            name='building_length_feet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='householdsurvey',
            name='building_width_feet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
