# Generated by Django 6.0 on 2025-12-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0017_householdsurvey_building_length_feet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial',
            name='plinth_or_srilt_height_meter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='householdsurvey',
            name='building_area_sqft',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='householdsurvey',
            name='flood_depth_from_survey_meter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='householdsurvey',
            name='maximum_flood_height_meter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='householdsurvey',
            name='plinth_or_srilt_height_meter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='householdsurvey',
            name='plinth_or_stilt_height_meter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
