# Generated by Django 6.0 on 2025-12-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0018_commercial_plinth_or_srilt_height_meter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='householdsurvey',
            name='plinth_or_srilt_height_meter',
        ),
    ]
