# Generated by Django 6.0 on 2025-12-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0019_remove_householdsurvey_plinth_or_srilt_height_meter'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdsurvey',
            name='loss_AgriLivli',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
