# Generated by Django 6.0 on 2025-12-30 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0020_householdsurvey_loss_agrilivli'),
        ('village_profile', '0007_district_village_mapping_district_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk_Assessment_with_MRD_mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.CharField(blank=True, max_length=255, null=True)),
                ('village_code', models.CharField(blank=True, max_length=100, null=True)),
                ('hazard', models.CharField(blank=True, max_length=100, null=True)),
                ('exposure_type', models.CharField(blank=True, max_length=100, null=True)),
                ('total_exposure_value_inr_crore', models.CharField(blank=True, max_length=100, null=True)),
                ('loss_inr_crore', models.CharField(blank=True, max_length=100, null=True)),
                ('loss_percent_wrt_exposure_value', models.CharField(blank=True, max_length=100, null=True)),
                ('mrd_mapping', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village_profile.tblvillage')),
            ],
        ),
    ]
