# Generated by Django 5.2.9 on 2026-01-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0022_householdsurvey_toilet_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdsurvey',
            name='adequate_water_supply',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
