# Generated by Django 5.2.9 on 2026-01-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0023_householdsurvey_adequate_water_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdsurvey',
            name='JJM_or_other_taped_water_connection',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='householdsurvey',
            name='sludge_be_disposed_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='householdsurvey',
            name='type_of_toilet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
