# Generated by Django 5.2.9 on 2026-01-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0024_householdsurvey_jjm_or_other_taped_water_connection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial',
            name='erosion_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='critical_facility',
            name='erosion_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='householdsurvey',
            name='erosion_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
