# Generated by Django 5.2.9 on 2026-01-24 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0025_commercial_erosion_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='householdsurvey',
            name='dist_code',
        ),
        migrations.RemoveField(
            model_name='householdsurvey',
            name='loan_class_1',
        ),
        migrations.RemoveField(
            model_name='householdsurvey',
            name='name_of_person',
        ),
    ]
