# Generated by Django 5.2.9 on 2026-01-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0026_remove_householdsurvey_dist_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgricultureUnitCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_typology', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('type_id', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('cost_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agriculture_unit_cost',
            },
        ),
        migrations.CreateModel(
            name='RoadUnitCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_typology', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('type_id', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('cost_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'road_unit_cost',
            },
        ),
        migrations.AlterField(
            model_name='attributemapping',
            name='model_name',
            field=models.CharField(choices=[('HouseholdSurvey', 'Household Survey'), ('Commercial', 'Commercial'), ('Transformer', 'Transformer'), ('Critical_Facility', 'Critical_Facility'), ('ElectricPole', 'ElectricPole'), ('VillageListOfAllTheDistricts', 'VillageListOfAllTheDistricts'), ('VillageRoadInfo', 'VillageRoadInfo'), ('BridgeSurvey', 'BridgeSurvey'), ('others', 'others')], max_length=50),
        ),
    ]
