# Generated by Django 5.2.9 on 2026-01-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0027_agricultureunitcost_roadunitcost_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgricultureUnitCost',
        ),
        migrations.AlterField(
            model_name='roadunitcost',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='roadunitcost',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterModelTable(
            name='roadunitcost',
            table=None,
        ),
    ]
