# Generated by Django 5.2.9 on 2026-01-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0028_delete_agricultureunitcost_alter_roadunitcost_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadunitcost',
            name='type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
