# Generated by Django 5.2.9 on 2026-01-26 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0029_alter_roadunitcost_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bridgesurvey',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bridgesurvey',
            name='district_name',
        ),
        migrations.RemoveField(
            model_name='bridgesurvey',
            name='form_id',
        ),
        migrations.RemoveField(
            model_name='bridgesurvey',
            name='geometry',
        ),
        migrations.RemoveField(
            model_name='bridgesurvey',
            name='polygon_id',
        ),
        migrations.RemoveField(
            model_name='bridgesurvey',
            name='spatial_id',
        ),
        migrations.RemoveField(
            model_name='bridgesurvey',
            name='tab_id',
        ),
        migrations.RemoveField(
            model_name='bridgesurvey',
            name='tab_name',
        ),
        migrations.RemoveField(
            model_name='bridgesurvey',
            name='under_id',
        ),
        migrations.RemoveField(
            model_name='bridgesurvey',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='bridgesurvey',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='bridgesurvey',
            name='username',
        ),
    ]
