# Generated by Django 5.2.9 on 2026-01-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0030_remove_bridgesurvey_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridgesurvey',
            name='form_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bridgesurvey',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
