# Generated by Django 5.2.9 on 2026-01-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0031_bridgesurvey_form_id_bridgesurvey_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='villageroadinfo',
            name='eq_hazard',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='villageroadinfo',
            name='eq_hazard_mdr',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='villageroadinfo',
            name='eq_loss',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='villageroadinfo',
            name='flood_hazard_mdr',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='villageroadinfo',
            name='flood_loss',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='villageroadinfo',
            name='replacement_cost_inr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='villageroadinfo',
            name='road_type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villageroadinfo',
            name='road_width_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villageroadinfo',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='villageroadinfo',
            name='wind_hazard',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='villageroadinfo',
            name='wind_hazard_mdr',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='villageroadinfo',
            name='wind_loss',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
    ]
