# Generated by Django 5.2.9 on 2026-01-27 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0032_villageroadinfo_eq_hazard_and_more'),
        ('village_profile', '0009_merge_20260109_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillageRoadInfoEQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
                ('district_code', models.CharField(max_length=20)),
                ('village_name', models.CharField(max_length=100)),
                ('village_code', models.CharField(max_length=20)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('road_surface_type', models.CharField(max_length=100)),
                ('road_constructed_by', models.CharField(max_length=100)),
                ('road_length_m', models.FloatField()),
                ('road_width_m', models.FloatField(blank=True, null=True)),
                ('road_type_id', models.IntegerField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('replacement_cost_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('eq_hazard', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('eq_hazard_mdr', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('eq_loss', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village_profile.tblvillage')),
            ],
        ),
        migrations.CreateModel(
            name='VillageRoadInfoWind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
                ('district_code', models.CharField(max_length=20)),
                ('village_name', models.CharField(max_length=100)),
                ('village_code', models.CharField(max_length=20)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('road_surface_type', models.CharField(max_length=100)),
                ('road_constructed_by', models.CharField(max_length=100)),
                ('road_length_m', models.FloatField()),
                ('road_width_m', models.FloatField(blank=True, null=True)),
                ('road_type_id', models.IntegerField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('replacement_cost_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('wind_hazard', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('wind_hazard_mdr', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('wind_loss', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village_profile.tblvillage')),
            ],
        ),
    ]
