# Generated by Django 5.2.9 on 2026-01-27 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0033_villageroadinfoeq_villageroadinfowind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villageroadinfo',
            name='eq_hazard',
        ),
        migrations.RemoveField(
            model_name='villageroadinfo',
            name='eq_hazard_mdr',
        ),
        migrations.RemoveField(
            model_name='villageroadinfo',
            name='eq_loss',
        ),
        migrations.RemoveField(
            model_name='villageroadinfo',
            name='wind_hazard',
        ),
        migrations.RemoveField(
            model_name='villageroadinfo',
            name='wind_hazard_mdr',
        ),
        migrations.RemoveField(
            model_name='villageroadinfo',
            name='wind_loss',
        ),
    ]
