# Generated by Django 5.2.9 on 2026-01-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0034_remove_villageroadinfo_eq_hazard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='villageroadinfo',
            name='eq_hazard',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='villageroadinfo',
            name='eq_hazard_mdr',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='villageroadinfo',
            name='eq_loss',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='villageroadinfo',
            name='wind_hazard',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='villageroadinfo',
            name='wind_hazard_mdr',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='villageroadinfo',
            name='wind_loss',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
    ]
