# Generated by Django 5.2.9 on 2026-01-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0035_villageroadinfo_eq_hazard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_data_vdmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('survey', 'Survey'), ('gis', 'GIS'), ('hazard', 'Hazard'), ('photos', 'Photos')], max_length=20)),
                ('type_of_data', models.CharField(max_length=500)),
                ('format', models.CharField(max_length=100)),
                ('selection_level', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_files', models.PositiveIntegerField(default=1)),
                ('remark', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
