# Generated by Django 5.2.9 on 2026-01-28 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0035_villageroadinfo_eq_hazard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villageroadinfo',
            name='eq_hazard',
        ),
        migrations.RemoveField(
            model_name='villageroadinfo',
            name='eq_hazard_mdr',
        ),
        migrations.RemoveField(
            model_name='villageroadinfo',
            name='eq_loss',
        ),
        migrations.RemoveField(
            model_name='villageroadinfo',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='villageroadinfo',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='villageroadinfo',
            name='wind_hazard',
        ),
        migrations.RemoveField(
            model_name='villageroadinfo',
            name='wind_hazard_mdr',
        ),
        migrations.RemoveField(
            model_name='villageroadinfo',
            name='wind_loss',
        ),
        migrations.RemoveField(
            model_name='villageroadinfoeq',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='villageroadinfoeq',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='villageroadinfowind',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='villageroadinfowind',
            name='longitude',
        ),
    ]
