# Generated by Django 5.2.9 on 2026-01-28 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0036_remove_villageroadinfo_eq_hazard_and_more'),
        ('village_profile', '0009_merge_20260109_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='villageAgricultureLandErosionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
                ('district_code', models.CharField(max_length=20)),
                ('village_name', models.CharField(max_length=100)),
                ('village_code', models.CharField(max_length=20)),
                ('total_area_sqm', models.FloatField()),
                ('erosion_class', models.CharField(max_length=50)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village_profile.tblvillage')),
            ],
        ),
        migrations.CreateModel(
            name='villageAgricultureLandFloodInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
                ('district_code', models.CharField(max_length=20)),
                ('village_name', models.CharField(max_length=100)),
                ('village_code', models.CharField(max_length=20)),
                ('total_area_sqm', models.FloatField()),
                ('flood_depth_m', models.FloatField(blank=True, null=True)),
                ('flood_class', models.CharField(max_length=50)),
                ('unit_cost_per_sqm', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_replacement_cost_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('flood_hazard_mdr', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('flood_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village_profile.tblvillage')),
            ],
        ),
    ]
