# Generated by Django 5.2.9 on 2026-01-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0038_villageagriculturelandeqinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgricultureLandCostMaping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_type', models.CharField(max_length=100)),
                ('unit_cost_per_sqm', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
        ),
    ]
