# Generated by Django 5.2.9 on 2026-01-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0039_agriculturelandcostmaping'),
    ]

    operations = [
        migrations.AddField(
            model_name='villageagriculturelanderosioninfo',
            name='total_replacement_cost_inr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='villageagriculturelanderosioninfo',
            name='unit_cost_per_sqm',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
