# Generated by Django 5.2.9 on 2026-01-29 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0036_upload_data_vdmp'),
        ('vdmp_dashboard', '0040_villageagriculturelanderosioninfo_total_replacement_cost_inr_and_more'),
    ]

    operations = [
    ]
