# Generated by Django 5.2.9 on 2026-01-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0040_villageagriculturelanderosioninfo_total_replacement_cost_inr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='agricultureLandEQMDRMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eq_hazard', models.FloatField()),
                ('mdr', models.DecimalField(decimal_places=8, max_digits=10)),
                ('crop_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='agricultureLandFloodMDRMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flood_depth_m', models.FloatField()),
                ('mdr', models.DecimalField(decimal_places=8, max_digits=10)),
                ('crop_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='agricultureLandWindMDRMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind_hazard', models.FloatField()),
                ('mdr', models.DecimalField(decimal_places=8, max_digits=10)),
                ('crop_type', models.CharField(max_length=100)),
            ],
        ),
    ]
