# Generated by Django 5.2.9 on 2026-01-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0041_merge_20260129_1745'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgricultureLandCostMaping',
        ),
        migrations.RemoveField(
            model_name='villageagriculturelanderosioninfo',
            name='village',
        ),
        migrations.RemoveField(
            model_name='villageagriculturelandfloodinfo',
            name='village',
        ),
        migrations.RemoveField(
            model_name='villageagriculturelandwindinfo',
            name='village',
        ),
        migrations.AddField(
            model_name='villageroadinfo',
            name='eq_hazard',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='villageroadinfo',
            name='eq_hazard_mdr',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='villageroadinfo',
            name='eq_loss',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='villageroadinfo',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='villageroadinfo',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='villageroadinfo',
            name='wind_hazard',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='villageroadinfo',
            name='wind_hazard_mdr',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='villageroadinfo',
            name='wind_loss',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='villageroadinfoeq',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='villageroadinfoeq',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='villageroadinfowind',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='villageroadinfowind',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='villageAgricultureLandEQInfo',
        ),
        migrations.DeleteModel(
            name='villageAgricultureLandErosionInfo',
        ),
        migrations.DeleteModel(
            name='villageAgricultureLandFloodInfo',
        ),
        migrations.DeleteModel(
            name='villageAgricultureLandWindInfo',
        ),
    ]
