# Generated by Django 5.2.9 on 2026-01-30 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0042_delete_agriculturelandcostmaping_and_more'),
        ('village_profile', '0009_merge_20260109_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgricultureLandCostMaping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_type', models.CharField(max_length=100)),
                ('unit_cost_per_sqm', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='villageroadinfo',
            name='eq_hazard',
        ),
        migrations.RemoveField(
            model_name='villageroadinfo',
            name='eq_hazard_mdr',
        ),
        migrations.RemoveField(
            model_name='villageroadinfo',
            name='eq_loss',
        ),
        migrations.RemoveField(
            model_name='villageroadinfo',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='villageroadinfo',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='villageroadinfo',
            name='wind_hazard',
        ),
        migrations.RemoveField(
            model_name='villageroadinfo',
            name='wind_hazard_mdr',
        ),
        migrations.RemoveField(
            model_name='villageroadinfo',
            name='wind_loss',
        ),
        migrations.RemoveField(
            model_name='villageroadinfoeq',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='villageroadinfoeq',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='villageroadinfowind',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='villageroadinfowind',
            name='longitude',
        ),
        migrations.CreateModel(
            name='villageAgricultureLandEQInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
                ('district_code', models.CharField(max_length=20)),
                ('village_name', models.CharField(max_length=100)),
                ('village_code', models.CharField(max_length=20)),
                ('total_area_sqm', models.FloatField()),
                ('eq_hazard', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('eq_hazard_mdr', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('unit_cost_per_sqm', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_replacement_cost_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('eq_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village_profile.tblvillage')),
            ],
        ),
        migrations.CreateModel(
            name='villageAgricultureLandErosionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
                ('district_code', models.CharField(max_length=20)),
                ('village_name', models.CharField(max_length=100)),
                ('village_code', models.CharField(max_length=20)),
                ('total_area_sqm', models.FloatField()),
                ('erosion_class', models.CharField(max_length=50)),
                ('unit_cost_per_sqm', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_replacement_cost_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village_profile.tblvillage')),
            ],
        ),
        migrations.CreateModel(
            name='villageAgricultureLandFloodInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
                ('district_code', models.CharField(max_length=20)),
                ('village_name', models.CharField(max_length=100)),
                ('village_code', models.CharField(max_length=20)),
                ('total_area_sqm', models.FloatField()),
                ('flood_depth_m', models.FloatField(blank=True, null=True)),
                ('flood_class', models.CharField(max_length=50)),
                ('unit_cost_per_sqm', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_replacement_cost_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('flood_hazard_mdr', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('flood_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village_profile.tblvillage')),
            ],
        ),
        migrations.CreateModel(
            name='villageAgricultureLandWindInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
                ('district_code', models.CharField(max_length=20)),
                ('village_name', models.CharField(max_length=100)),
                ('village_code', models.CharField(max_length=20)),
                ('total_area_sqm', models.FloatField()),
                ('wind_hazard', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('wind_hazard_mdr', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('unit_cost_per_sqm', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_replacement_cost_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('wind_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village_profile.tblvillage')),
            ],
        ),
    ]
