# Generated by Django 5.2.9 on 2026-02-03 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0041_agriculturelandeqmdrmapping_and_more'),
        ('vdmp_dashboard', '0043_agriculturelandcostmaping_and_more'),
    ]

    operations = [
    ]
