# Generated by Django 5.2.9 on 2026-02-04 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vdmp_dashboard", "0044_merge_20260203_1444"),
        ("vdmp_dashboard", "0044_merge_20260203_1503"),
    ]

    operations = []
