# Generated by Django 5.2.9 on 2026-02-06 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0045_merge_20260204_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vdmp_maps_data',
            name='earthquake_hazard',
        ),
        migrations.RemoveField(
            model_name='vdmp_maps_data',
            name='flood_erosion',
        ),
        migrations.RemoveField(
            model_name='vdmp_maps_data',
            name='wind_hazard',
        ),
    ]
