# Generated by Django 5.2.9 on 2026-02-06 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0046_remove_vdmp_maps_data_earthquake_hazard_and_more'),
        ('village_profile', '0009_merge_20260109_1813'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VDMP_Maps_Data',
            new_name='VdmpVillageMapData',
        ),
        migrations.AlterModelTable(
            name='vdmpvillagemapdata',
            table='vdmp_village_map_Data',
        ),
        migrations.AddField(
            model_name='vdmpvillagemapdata',
            name='flood_erosion',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='maps/flood_erosion/'),
        ),
        migrations.CreateModel(
            name='VdmDistrictMapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind_hazard', models.FileField(blank=True, max_length=255, null=True, upload_to='maps/wind_hazard/')),
                ('earthquake_hazard', models.FileField(blank=True, max_length=255, null=True, upload_to='maps/earthquake_hazard/')),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='village_profile.tbldistrict')),
            ],
            options={
                'db_table': 'vdm_district_map_data',
            },
        ),
    ]
