# Generated by Django 5.2.9 on 2026-02-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0047_rename_vdmp_maps_data_and_add_district_map_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdmdistrictmapdata',
            name='hazard_calendar',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='maps/hazard_calendar/'),
        ),
    ]
