# Generated by Django 5.2.9 on 2026-02-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0047_rename_vdmp_maps_data_and_add_district_map_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='roadFloodMDRMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flood_depth_m', models.FloatField()),
                ('mdr', models.DecimalField(decimal_places=8, max_digits=10)),
                ('road_surface_type', models.CharField(max_length=100)),
            ],
        ),
    ]
