# Generated by Django 5.2.9 on 2026-02-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0048_roadfloodmdrmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villageagriculturelandeqinfo',
            name='eq_hazard',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='villageagriculturelandeqinfo',
            name='eq_hazard_mdr',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='villageagriculturelandeqinfo',
            name='unit_cost_per_sqm',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='villageagriculturelandfloodinfo',
            name='unit_cost_per_sqm',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='villageagriculturelandwindinfo',
            name='unit_cost_per_sqm',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='villageagriculturelandwindinfo',
            name='wind_hazard',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='villageagriculturelandwindinfo',
            name='wind_hazard_mdr',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='villageroadinfo',
            name='flood_hazard_mdr',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='villageroadinfo',
            name='flood_loss',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='villageroadinfo',
            name='replacement_cost_inr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='villageroadinfo',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='villageroadinfoeq',
            name='eq_hazard',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='villageroadinfoeq',
            name='eq_hazard_mdr',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='villageroadinfoeq',
            name='eq_loss',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='villageroadinfoeq',
            name='replacement_cost_inr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='villageroadinfoeq',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='villageroadinfowind',
            name='replacement_cost_inr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='villageroadinfowind',
            name='wind_hazard',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='villageroadinfowind',
            name='wind_hazard_mdr',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='villageroadinfowind',
            name='wind_loss',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
