# Generated by Django 5.2.9 on 2026-02-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0049_alter_villageagriculturelandeqinfo_eq_hazard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformer',
            name='condition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transformer',
            name='fencing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transformer',
            name='material',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
