# Generated by Django 5.2.9 on 2026-02-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0050_transformer_condition_transformer_fencing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformer',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
