# Generated by Django 5.2.9 on 2026-02-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0051_transformer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricpole',
            name='condition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='electricpole',
            name='material',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
