# Generated by Django 5.2.9 on 2026-02-09 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0052_electricpole_condition_electricpole_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricpole',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='electricpole',
            name='material',
        ),
    ]
