# Generated by Django 5.2.9 on 2026-02-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0053_remove_electricpole_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricpole',
            name='erosion_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transformer',
            name='erosion_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
