# Generated by Django 5.2.9 on 2026-02-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0048_vdmdistrictmapdata_hazard_calendar'),
        ('vdmp_dashboard', '0054_electricpole_erosion_value_transformer_erosion_value'),
    ]

    operations = [
    ]
