# Generated by Django 5.2.9 on 2026-02-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vdmp_dashboard", "0055_merge_20260209_1550"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agriculturelandeqmdrmapping",
            name="mdr",
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name="agriculturelandwindmdrmapping",
            name="mdr",
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
    ]
