# Generated by Django 5.2.9 on 2026-02-25 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0058_villageroadinfo_asset_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villageroadinfo',
            name='asset_type',
        ),
    ]
