# Generated by Django 5.2.9 on 2026-02-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0059_remove_villageroadinfo_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='villageroadinfo',
            name='asset_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
