# Generated by Django 5.2.9 on 2026-02-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0060_villageroadinfo_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherdata',
            name='village_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
