# Generated by Django 5.2.9 on 2026-02-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdmp_dashboard', '0062_transformer_form_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherdata',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherdata',
            name='height_of_asset_above_ground_ft',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherdata',
            name='plinth_height_in_ft',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
